/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareReminderSnapshot {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'recurrence' : string,
  'petId' : string,
}
export type ExternalBlob = Uint8Array;
export interface HealthEventSnapshot {
  'id' : string,
  'date' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'documentBlobs' : Array<ExternalBlob>,
  'petId' : string,
  'eventType' : string,
}
export interface PetProfileSnapshot {
  'id' : string,
  'age' : bigint,
  'weight' : bigint,
  'photoBlob' : ExternalBlob,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'sharedWith' : Array<Principal>,
  'updatedAt' : bigint,
  'notes' : string,
  'breed' : string,
  'species' : string,
}
export interface SymptomAssessmentSnapshot {
  'id' : string,
  'photoBlob' : [] | [ExternalBlob],
  'owner' : Principal,
  'createdAt' : bigint,
  'assessmentResult' : string,
  'petId' : string,
  'symptomDescription' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCareReminder' : ActorMethod<[CareReminderSnapshot], string>,
  'addHealthEvent' : ActorMethod<[HealthEventSnapshot], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPetProfile' : ActorMethod<[PetProfileSnapshot], string>,
  'deleteCareReminder' : ActorMethod<[string], undefined>,
  'deleteHealthEvent' : ActorMethod<[string], undefined>,
  'deletePetProfile' : ActorMethod<[string], undefined>,
  'generateSitterToken' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareReminders' : ActorMethod<[string], Array<CareReminderSnapshot>>,
  'getHealthEvents' : ActorMethod<[string], Array<HealthEventSnapshot>>,
  'getPetProfile' : ActorMethod<[string], [] | [PetProfileSnapshot]>,
  'getPetProfiles' : ActorMethod<[], Array<PetProfileSnapshot>>,
  'getPetSummaryByToken' : ActorMethod<[string], PetProfileSnapshot>,
  'getSymptomAssessments' : ActorMethod<
    [string],
    Array<SymptomAssessmentSnapshot>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markReminderCompleted' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitSymptomReport' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    string
  >,
  'updatePetProfile' : ActorMethod<[string, PetProfileSnapshot], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];