/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CareReminderSnapshot = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'recurrence' : IDL.Text,
  'petId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HealthEventSnapshot = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'documentBlobs' : IDL.Vec(ExternalBlob),
  'petId' : IDL.Text,
  'eventType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PetProfileSnapshot = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'weight' : IDL.Nat,
  'photoBlob' : ExternalBlob,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sharedWith' : IDL.Vec(IDL.Principal),
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'breed' : IDL.Text,
  'species' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SymptomAssessmentSnapshot = IDL.Record({
  'id' : IDL.Text,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'assessmentResult' : IDL.Text,
  'petId' : IDL.Text,
  'symptomDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCareReminder' : IDL.Func([CareReminderSnapshot], [IDL.Text], []),
  'addHealthEvent' : IDL.Func([HealthEventSnapshot], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPetProfile' : IDL.Func([PetProfileSnapshot], [IDL.Text], []),
  'deleteCareReminder' : IDL.Func([IDL.Text], [], []),
  'deleteHealthEvent' : IDL.Func([IDL.Text], [], []),
  'deletePetProfile' : IDL.Func([IDL.Text], [], []),
  'generateSitterToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareReminders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CareReminderSnapshot)],
      ['query'],
    ),
  'getHealthEvents' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthEventSnapshot)],
      ['query'],
    ),
  'getPetProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PetProfileSnapshot)],
      ['query'],
    ),
  'getPetProfiles' : IDL.Func([], [IDL.Vec(PetProfileSnapshot)], ['query']),
  'getPetSummaryByToken' : IDL.Func(
      [IDL.Text],
      [PetProfileSnapshot],
      ['query'],
    ),
  'getSymptomAssessments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SymptomAssessmentSnapshot)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markReminderCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitSymptomReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'updatePetProfile' : IDL.Func([IDL.Text, PetProfileSnapshot], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CareReminderSnapshot = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'recurrence' : IDL.Text,
    'petId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HealthEventSnapshot = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'documentBlobs' : IDL.Vec(ExternalBlob),
    'petId' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PetProfileSnapshot = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'weight' : IDL.Nat,
    'photoBlob' : ExternalBlob,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sharedWith' : IDL.Vec(IDL.Principal),
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'breed' : IDL.Text,
    'species' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SymptomAssessmentSnapshot = IDL.Record({
    'id' : IDL.Text,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'assessmentResult' : IDL.Text,
    'petId' : IDL.Text,
    'symptomDescription' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCareReminder' : IDL.Func([CareReminderSnapshot], [IDL.Text], []),
    'addHealthEvent' : IDL.Func([HealthEventSnapshot], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPetProfile' : IDL.Func([PetProfileSnapshot], [IDL.Text], []),
    'deleteCareReminder' : IDL.Func([IDL.Text], [], []),
    'deleteHealthEvent' : IDL.Func([IDL.Text], [], []),
    'deletePetProfile' : IDL.Func([IDL.Text], [], []),
    'generateSitterToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareReminders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CareReminderSnapshot)],
        ['query'],
      ),
    'getHealthEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthEventSnapshot)],
        ['query'],
      ),
    'getPetProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PetProfileSnapshot)],
        ['query'],
      ),
    'getPetProfiles' : IDL.Func([], [IDL.Vec(PetProfileSnapshot)], ['query']),
    'getPetSummaryByToken' : IDL.Func(
        [IDL.Text],
        [PetProfileSnapshot],
        ['query'],
      ),
    'getSymptomAssessments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SymptomAssessmentSnapshot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markReminderCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitSymptomReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'updatePetProfile' : IDL.Func([IDL.Text, PetProfileSnapshot], [], []),
  });
};

export const init = ({ IDL }) => { return []; };