/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SymptomAssessmentSnapshot {
    id: string;
    photoBlob?: ExternalBlob;
    owner: Principal;
    createdAt: bigint;
    assessmentResult: string;
    petId: string;
    symptomDescription: string;
}
export interface PetProfileSnapshot {
    id: string;
    age: bigint;
    weight: bigint;
    photoBlob: ExternalBlob;
    owner: Principal;
    name: string;
    createdAt: bigint;
    sharedWith: Array<Principal>;
    updatedAt: bigint;
    notes: string;
    breed: string;
    species: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface HealthEventSnapshot {
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    documentBlobs: Array<ExternalBlob>;
    petId: string;
    eventType: string;
}
export interface CareReminderSnapshot {
    id: string;
    title: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate: bigint;
    recurrence: string;
    petId: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCareReminder(reminder: CareReminderSnapshot): Promise<string>;
    addHealthEvent(event: HealthEventSnapshot): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPetProfile(profile: PetProfileSnapshot): Promise<string>;
    deleteCareReminder(reminderId: string): Promise<void>;
    deleteHealthEvent(eventId: string): Promise<void>;
    deletePetProfile(petId: string): Promise<void>;
    generateSitterToken(petId: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCareReminders(petId: string): Promise<Array<CareReminderSnapshot>>;
    getHealthEvents(petId: string): Promise<Array<HealthEventSnapshot>>;
    getPetProfile(petId: string): Promise<PetProfileSnapshot | null>;
    getPetProfiles(): Promise<Array<PetProfileSnapshot>>;
    getPetSummaryByToken(token: string): Promise<PetProfileSnapshot>;
    getSymptomAssessments(petId: string): Promise<Array<SymptomAssessmentSnapshot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markReminderCompleted(reminderId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitSymptomReport(petId: string, description: string, photoBlob: ExternalBlob | null): Promise<string>;
    updatePetProfile(petId: string, profile: PetProfileSnapshot): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, HealthEventSnapshot as _HealthEventSnapshot, PetProfileSnapshot as _PetProfileSnapshot, SymptomAssessmentSnapshot as _SymptomAssessmentSnapshot, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCareReminder(arg0: CareReminderSnapshot): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCareReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCareReminder(arg0);
            return result;
        }
    }
    async addHealthEvent(arg0: HealthEventSnapshot): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addHealthEvent(await to_candid_HealthEventSnapshot_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHealthEvent(await to_candid_HealthEventSnapshot_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPetProfile(arg0: PetProfileSnapshot): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPetProfile(await to_candid_PetProfileSnapshot_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPetProfile(await to_candid_PetProfileSnapshot_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCareReminder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCareReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCareReminder(arg0);
            return result;
        }
    }
    async deleteHealthEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHealthEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHealthEvent(arg0);
            return result;
        }
    }
    async deletePetProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePetProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePetProfile(arg0);
            return result;
        }
    }
    async generateSitterToken(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSitterToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSitterToken(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareReminders(arg0: string): Promise<Array<CareReminderSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareReminders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareReminders(arg0);
            return result;
        }
    }
    async getHealthEvents(arg0: string): Promise<Array<HealthEventSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthEvents(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthEvents(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPetProfile(arg0: string): Promise<PetProfileSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPetProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPetProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPetProfiles(): Promise<Array<PetProfileSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPetProfiles();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPetProfiles();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPetSummaryByToken(arg0: string): Promise<PetProfileSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getPetSummaryByToken(arg0);
                return from_candid_PetProfileSnapshot_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPetSummaryByToken(arg0);
            return from_candid_PetProfileSnapshot_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSymptomAssessments(arg0: string): Promise<Array<SymptomAssessmentSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSymptomAssessments(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSymptomAssessments(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markReminderCompleted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markReminderCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markReminderCompleted(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitSymptomReport(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSymptomReport(arg0, arg1, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSymptomReport(arg0, arg1, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePetProfile(arg0: string, arg1: PetProfileSnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePetProfile(arg0, await to_candid_PetProfileSnapshot_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePetProfile(arg0, await to_candid_PetProfileSnapshot_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HealthEventSnapshot_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthEventSnapshot): Promise<HealthEventSnapshot> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_PetProfileSnapshot_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PetProfileSnapshot): Promise<PetProfileSnapshot> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_SymptomAssessmentSnapshot_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SymptomAssessmentSnapshot): Promise<SymptomAssessmentSnapshot> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PetProfileSnapshot]): Promise<PetProfileSnapshot | null> {
    return value.length === 0 ? null : await from_candid_PetProfileSnapshot_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    documentBlobs: Array<_ExternalBlob>;
    petId: string;
    eventType: string;
}): Promise<{
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    documentBlobs: Array<ExternalBlob>;
    petId: string;
    eventType: string;
}> {
    return {
        id: value.id,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        documentBlobs: await from_candid_vec_n22(_uploadFile, _downloadFile, value.documentBlobs),
        petId: value.petId,
        eventType: value.eventType
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    weight: bigint;
    photoBlob: _ExternalBlob;
    owner: Principal;
    name: string;
    createdAt: bigint;
    sharedWith: Array<Principal>;
    updatedAt: bigint;
    notes: string;
    breed: string;
    species: string;
}): Promise<{
    id: string;
    age: bigint;
    weight: bigint;
    photoBlob: ExternalBlob;
    owner: Principal;
    name: string;
    createdAt: bigint;
    sharedWith: Array<Principal>;
    updatedAt: bigint;
    notes: string;
    breed: string;
    species: string;
}> {
    return {
        id: value.id,
        age: value.age,
        weight: value.weight,
        photoBlob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.photoBlob),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        sharedWith: value.sharedWith,
        updatedAt: value.updatedAt,
        notes: value.notes,
        breed: value.breed,
        species: value.species
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    photoBlob: [] | [_ExternalBlob];
    owner: Principal;
    createdAt: bigint;
    assessmentResult: string;
    petId: string;
    symptomDescription: string;
}): Promise<{
    id: string;
    photoBlob?: ExternalBlob;
    owner: Principal;
    createdAt: bigint;
    assessmentResult: string;
    petId: string;
    symptomDescription: string;
}> {
    return {
        id: value.id,
        photoBlob: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.photoBlob)),
        owner: value.owner,
        createdAt: value.createdAt,
        assessmentResult: value.assessmentResult,
        petId: value.petId,
        symptomDescription: value.symptomDescription
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthEventSnapshot>): Promise<Array<HealthEventSnapshot>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HealthEventSnapshot_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PetProfileSnapshot>): Promise<Array<PetProfileSnapshot>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PetProfileSnapshot_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SymptomAssessmentSnapshot>): Promise<Array<SymptomAssessmentSnapshot>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SymptomAssessmentSnapshot_n29(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HealthEventSnapshot_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthEventSnapshot): Promise<_HealthEventSnapshot> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_PetProfileSnapshot_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetProfileSnapshot): Promise<_PetProfileSnapshot> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    weight: bigint;
    photoBlob: ExternalBlob;
    owner: Principal;
    name: string;
    createdAt: bigint;
    sharedWith: Array<Principal>;
    updatedAt: bigint;
    notes: string;
    breed: string;
    species: string;
}): Promise<{
    id: string;
    age: bigint;
    weight: bigint;
    photoBlob: _ExternalBlob;
    owner: Principal;
    name: string;
    createdAt: bigint;
    sharedWith: Array<Principal>;
    updatedAt: bigint;
    notes: string;
    breed: string;
    species: string;
}> {
    return {
        id: value.id,
        age: value.age,
        weight: value.weight,
        photoBlob: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photoBlob),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        sharedWith: value.sharedWith,
        updatedAt: value.updatedAt,
        notes: value.notes,
        breed: value.breed,
        species: value.species
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    documentBlobs: Array<ExternalBlob>;
    petId: string;
    eventType: string;
}): Promise<{
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    documentBlobs: Array<_ExternalBlob>;
    petId: string;
    eventType: string;
}> {
    return {
        id: value.id,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        documentBlobs: await to_candid_vec_n10(_uploadFile, _downloadFile, value.documentBlobs),
        petId: value.petId,
        eventType: value.eventType
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
